import { Poppins } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "./components/ModalProvider";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
        inmaintabuse="1"
        data-new-gr-c-s-check-loaded="14.1215.0"
        data-gr-ext-installed=""
      >
        <ToastContainer />
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
